module.exports = {
    SEND: 0,
    SIGNATURE: 1,
    DELEGATE: 2,
    VOTE: 3,
    MULTI: 4,
    IPFS: 5,
    REGISTER: 6,
    VERIFY: 7,
    CREATE_ATTRIBUTE: 8,
    UPDATE_ATTRIBUTE: 9,
    REQUEST_ATTRIBUTE_VALIDATION: 10,
    APPROVE_ATTRIBUTE_VALIDATION_REQUEST: 11,
    DECLINE_ATTRIBUTE_VALIDATION_REQUEST: 12,
    NOTARIZE_ATTRIBUTE_VALIDATION_REQUEST: 13,
    REJECT_ATTRIBUTE_VALIDATION_REQUEST: 14,
    REQUEST_ATTRIBUTE_SHARE: 15,
    SHARE_ATTRIBUTE: 16,
    APPROVE_ATTRIBUTE_SHARE: 17,
    CONSUME_ATTRIBUTE: 18,
    RUN_REWARD_ROUND: 19,
    REWARD: 20,
    UPDATE_REWARD_ROUND_TO_COMPLETE: 21
};

'use strict';
