'use strict';

module.exports = {
    SEND: 0,
    SIGNATURE: 1,
    DELEGATE: 2,
    VOTE: 3,
    MULTI: 4,
    IPFS: 5,
    REGISTER: 6,
    VERIFY: 7,
    CREATE_ATTRIBUTE: 8,
    REQUEST_ATTRIBUTE_VALIDATION: 9,
    VALIDATE_ATTRIBUTE: 10,
    REQUEST_ATTRIBUTE_SHARE: 11,
    SHARE_ATTRIBUTE: 12,
    APPROVE_ATTRIBUTE_SHARE: 13,
    CONSUME_ATTRIBUTE: 14,
    RUN_REWARD_ROUND: 15,
    REWARD: 16,
    UPDATE_REWARD_ROUND_TO_COMPLETE: 17
};
