module.exports = {
    SEND: 0,
    SIGNATURE: 1,
    DELEGATE: 2,
    VOTE: 3,
    MULTI: 4,
    IPFS: 5,
    REGISTER: 6,
    VERIFY: 7,
    CREATE_ATTRIBUTE: 8,
    UPDATE_ATTRIBUTE: 9,
    REQUEST_ATTRIBUTE_VALIDATION: 10,
    VALIDATE_ATTRIBUTE: 11,
    REQUEST_ATTRIBUTE_SHARE: 12,
    SHARE_ATTRIBUTE: 13,
    APPROVE_ATTRIBUTE_SHARE: 14,
    CONSUME_ATTRIBUTE: 15,
    RUN_REWARD_ROUND: 16,
    REWARD: 17,
    UPDATE_REWARD_ROUND_TO_COMPLETE: 18
};

'use strict';
